console.time("Time taken by your code to execute: ");
console.log("This is Pallavi");
console.log(90);
console.log(44+6);
console.log(true);
console.log([1,2,3,4,5,6]);
console.log({naam: "Pallavi" , marks: 100});
console.table({naam: "Pallavi" , marks: 100});
console.warn("This is warning");
//console.clear();
console.timeEnd("Time taken by your code to execute: ");